---
- name: Install nginx
  hosts: tp1
  become: true

  tasks:
  - name: Install nginx
    dnf:
      name: nginx
      state: present

  - name: Insert Index Page
    template:
      src: index.html.j2
      dest: /usr/share/nginx/html/index.html
      
  - name: Transfer nginx config to target
    template:
      src: nginx.conf
      dest: /etc/nginx/conf.d/nginx.conf

  - name: Start NGiNX
    service:
      name: nginx
      state: started