Vagrant.configure("2") do |config|

  config.vm.box = "marcinbojko/rockylinux9_arm64"
  config.vm.box_check_update = false 
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.provision "shell", path: "setup.sh"
  config.ssh.insert_key = false
  config.vm.provision "file", source: "/Users/dev/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.ssh.username = "vagrant"

  config.vm.define "first" do |first|
    first.vm.network "private_network", ip: "10.1.1.11"
  end

  config.vm.define "second" do |second|
    second.vm.network "private_network", ip: "10.1.1.12"
  end
end
